baseURL: 'https://autodaiiy.com'
languageCode: 'ko-kr'
title: '오토데일프릭스 블로그'
defaultContentLanguage: 'ko'
hasCJKLanguage: true
timeZone: 'Asia/Seoul'

params:
  description: '자동차와 경제, 그리고 일상에 대한 생각을 기록하는 개인 블로그입니다.'
  keywords: '블로그, 자동차, 경제, 일상, 생각'
  author: '오은진'

menu:
  main:
    - name: 'Home'
      url: '/'
      weight: 1
    - name: 'Tags'
      url: '/tags/'
      weight: 2
    - name: 'About'
      url: '/about/'
      weight: 3

taxonomies:
  tag: tags

outputs:
  home: ['HTML', 'RSS']
  page: ['HTML']
  section: ['HTML', 'RSS']

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: github
    lineNos: true

pagination:
  pagerSize: 10
  path: page

enableRobotsTXT: true

# SEO 최적화
googleAnalytics: ""
disableKinds: []

# URL 최적화
uglyURLs: false
canonifyURLs: false
relativeURLs: false
